apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 5s
      manageAlerts: true
      alertmanagerUid: alertmanager
    secureJsonData: {}
    
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: mcp_saas_production
    user: mcp_user
    isDefault: false
    editable: true
    jsonData:
      sslmode: require
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 15
      timescaledb: false
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
      
  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis:6379
    isDefault: false
    editable: true
    jsonData:
      client: standalone
      poolSize: 5
      timeout: 5
      pingInterval: 0
      pipelineWindow: 0
    secureJsonData:
      password: ${REDIS_PASSWORD}
